packages:
  - .

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
blockExoticSubdeps: true

allowBuilds:
  '@playwright/browser-chromium': true
  '@swc/core': true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true

overrides:
  '@docsearch/js': 4.6.3
  'mongodb>gcp-metadata': '-'
  'nunjucks>chokidar': '-'
