packages:
  - .

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
blockExoticSubdeps: true

onlyBuiltDependencies:
  - '@playwright/browser-chromium'
  - '@swc/core'
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp

overrides:
  '@docsearch/js': 4.6.3
  'mongodb>gcp-metadata': '-'
  'nunjucks>chokidar': '-'
